version: '2.1'

services:

  safehouse:
    build: .
    image: sofwerx/safehouse
    container_name: safehouse
    hostname: safehouse
    environment:
      ES_URL: ${ES_SAFEHOUSE_URL}
      ES_HTTP_AUTH: ${ES_SAFEHOUSE_HTTP_AUTH}
      ES_INDEX: ${ES_SAFEHOUSE_INDEX}
#    ports:
#      - 3000:3000

